language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: STraBhVvSlDHldbO6vxtZvMfgR7MvdDfE9HDJ82ifi0gWixzy1prYMJTETqi7tpFQsDeJkZkgqa7ngGSQcIoEtf8JWByOqWbq6K5iLRZRHcXvfvetpH3byVjnXsv3UgPOlvyTNoaS7srpZLpt3Tq7lm8yH3pqm5WXkqBoJhNnALPxvS6qi06Lif8d4uAeGRorYh0W5bGxUr2nuXXn8nzO7ICIFuCR53Xpn64J6FjSKryDmOl6vGgcupVFy3yK7810bv8AQ6qLwe6uoAnAPYSuFcgAAizCjEWMFdIW1aUDAsSa5VchCNz58oShrp9Y7PeGywfXFVKpkbOarpqsFYTJ/m6wnt92+B3p2Ssumi0sMet797gezkq/Z7U+WuwSl+E+NlIaG3o7hKgka62vBu9ybNOsAzEr3DAfNUh5FCUw+VChqV8OoiQxytVUDlEQ68Nxp0DfhBMlniJujJayJGjILzaGqM8lGyf6zObTVeSZG9jUW7ZeiKo9bP3T3RF5cvCxWjL2Vg/t8ctChEQdjkpBeTpBoWVQ6Cj8se41g53xUlX7zm8Q9dkmB+mmnDffLhfbco3szG5nHEQF6tsnkCtvC+dmPaJod9hm1PYJSNKZaio9rQGuMmHTXwwgAlNF/SmChrWzZ0c6qwh0VNXoYDtNQfqA5CN9I12fTqwuzMY+wQ=
  app: kevin-noteful-v4
  on:
    repo: thinkful-ei19/kevin-noteful-v4
